baseline_program: P_none
n_simulations: 1
parameter_level: simulation_settings
pregenerate_leaks: true
preseed_random: true
reference_program: P_OGI
version: "3.0"
write_data: true
start_date: [2017, 1, 1]
end_date: [2021, 12, 31]
