baseline_program: P_none
end_date:
  - 2021
  - 12
  - 31
input_directory: ./inputs
make_plots: true
n_processes: 6
n_simulations: 1
output_directory: ./outputs
parameter_level: simulation_settings
pregenerate_leaks: true
preseed_random: true
print_from_simulations: true
programs:
  P_OGI:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels:
      - OGI
    methods:
      OGI:
        RS: 2
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 600
          upfront: 0
        coverage:
          spatial: 0.9
          temporal: 0.9
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: OGI
        max_workday: 8
        measurement_scale: component
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.0362
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 30
        time: 120
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
    parameter_level: program
    program_name: P_OGI
    version: "3.0"
  P_aircraft:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels:
      - aircraft
      - OGI_FU
    methods:
      OGI_FU:
        RS: null
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 700
          upfront: 0
        coverage:
          spatial: 0.9
          temporal: 0.9
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: true
        label: OGI_FU
        max_workday: 8
        measurement_scale: component
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.0362
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 45
        time: 120
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
      aircraft:
        RS: 4
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 200
          upfront: 0
        coverage:
          spatial: 0.9
          temporal: 0.9
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: aircraft
        max_workday: 8
        measurement_scale: equipment
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 1
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 5
        time: 1
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
    parameter_level: program
    program_name: P_aircraft
    version: "3.0"
  P_drone:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels:
      - drone
      - OGI_FU
    methods:
      OGI_FU:
        RS: null
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 700
          upfront: 0
        coverage:
          spatial: 0.9
          temporal: 0.9
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: true
        label: OGI_FU
        max_workday: 8
        measurement_scale: component
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.0362
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 45
        time: 120
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
      drone:
        RS: 2
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 500
          upfront: 0
        coverage:
          spatial: 1.0
          temporal: 0.9
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: drone
        max_workday: 8
        measurement_scale: equipment
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.01
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 30
        time: 20
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
    parameter_level: program
    program_name: P_drone
    version: "3.0"
  P_none:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels: []
    methods: {}
    parameter_level: program
    program_name: P_none
    version: "3.0"
  P_truck:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels:
      - truck
      - OGI_FU
    methods:
      OGI_FU:
        RS: null
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 700
          upfront: 0
        coverage:
          spatial: 0.9
          temporal: 0.9
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: true
        label: OGI_FU
        max_workday: 8
        measurement_scale: component
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.0362
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 45
        time: 120
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
      truck:
        RS: 2
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 400
          upfront: 0
        coverage:
          spatial: 0.7
          temporal: 0.8
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: truck
        max_workday: 8
        measurement_scale: equipment
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.01
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 30
        time: 30
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
    parameter_level: program
    program_name: P_truck
    version: "3.0"
reference_program: P_OGI
start_date:
  - 2017
  - 1
  - 1
version: "3.0"
virtual_world:
  NRd: 365
  consider_weather: false
  emissions:
    LPR: 0.0065
    consider_venting: false
    leak_dist_params:
      - -2.776
      - 1.462
    leak_dist_type: lognorm
    leak_file: null
    leak_file_use: sample
    max_leak_rate: 100000.0
    units:
      - kilogram
      - hour
  infrastructure_file: facilities_alberta.csv
  n_init_days: null
  n_init_leaks_prob: null
  parameter_level: virtual_world
  repair_delay:
    type: default
    val:
      - 14.0
  site_samples: 500
  subtype_file: null
  version: "3.0"
  weather_file: weather_alberta.nc
  weather_is_hourly: true
write_data: true
