parameter_level: method
version: '2.0'
label: OGI
deployment_type: mobile
measurement_scale: component
sensor:
  type: OGI_camera_zim
  MDL: [0.24, 0.39]
is_follow_up: False
cost:
  per_day: 0
  per_site: 500
t_bw_sites:
  vals: [30]
RS: 4 
time: 120