name: 💬Discussions, 💭Ideas or❓Questions
description: Discussion/Brainstorming/Questions for LDAR-Sim
title: "[MISC] Brief Description"
labels: ["discussion"]
body:
- type: checkboxes
  attributes:
    label: Is this a duplicate/existing topic or question? 
    description: Please search to see if an issue already exists for this discussion/idea/question. 
    options:
    - label: I have searched to see if an issue already exists for this topic. 
      required: true  
- type: textarea
  attributes:
    label: Discussion/Brainstorming/Question description
    description: |
    Describe the topic of discussion or idea in detail as possible.

    **If question, please add additional "question" label. 
  validations:
    required: true
