EMIS_SUMMARY_DATA_COLS = [
    "Emissions ID",
    "Status",
    "Days Active",
    "Volume Emitted",
    "True Rate",
    "Measured Rate" "Date Began",
    "Initially Detected By",
    "Initially Detected Date",
    "Tagged",
    "Tagged By",
    "equipment",
]

EMIS_SUMMARY_FINAL_COL_ORDER = [
    "Emissions ID",
    "Site ID",
    "Equipment Group",
    "Equipment",
    "Status",
    "Days Active",
    "Date Began",
    "Date Repaired",
    "Volume Emitted",
    "True Rate",
    "Measured Rate",
    "Initially Detected By",
    "Initially Detected Date",
    "Tagged",
    "Tagged By",
]
