parameter_level: methods
version: "4.0"
label: OGI2
deployment_type: mobile
measurement_scale: component
sensor:
  type: OGI_camera_zim
  MDL: [0.24, 0.39] 
is_follow_up: False
cost:
  per_day: 0
  per_site: 500
t_bw_sites:
  vals: [30]
RS: 4
time: 120
