parameter_level: method
version: '3.0'
label: Continuous
deployment_type: stationary
measurement_scale: site
is_follow_up: False
sensor: 
  type: default
  MDL: [2]
cost:
  per_day: 4
coverage:
  spatial: 1
  temporal: 1
follow_up:
  preferred_method: '_placeholder_str_'
  delay: 30  # days
  instant_threshold: 5 # g/s
  instant_threshold_type: 'absolute'  # absolute/relative
  interaction_priority: 'threshold' # threshold/proportion
  min_followups: ['_placeholder_float_']  # list of values between 0.0 and 1.0
  min_followup_type: 'annual' # annual/campaign
  min_followup_days_to_end: 0 # days
  proportion: 1.0 # 0 to 1.0
  redundancy_filter: 'recent' # recent/max/average
  threshold: 0.0  # g/s
  threshold_type: 'absolute'  # absolute/relative
is_follow_up: False # True/False
reporting_delay: 2  # days