parameter_level: method
version: "3.0"
label: OGI_FU
deployment_type: mobile
measurement_scale: component
is_follow_up: True
sensor:
  type: default
  MDL: [0.5]
cost:
  per_site: 700
coverage:
  spatial: 1
  temporal: 1
t_bw_sites:
  vals: [45]
time: 120
