parameter_level: method
version: '2.0'
label: mobile_campaigns
deployment_type: mobile
measurement_scale: site
is_follow_up: False
sensor: 
  type: default
  MDL: [3]
cost:
  per_site: 100
coverage:
  spatial: 1.0
  temporal: 1
follow_up:
  preferred_method: '_placeholder_str_'
  delay: 0  # days
  instant_threshold: '_placeholder_float_'  # g/s
  instant_threshold_type: 'absolute'  # absolute/relative
  interaction_priority: 'threshold' # threshold/proportion
  min_followups: [1, 0.5, 0.5, 0.5]  # list of values between 0.0 and 1.0
  min_followup_type: 'campaign' # annual/campaign
  min_followup_days_to_end: 45 # days
  proportion: 1.0 # 0 to 1.0
  redundancy_filter: 'recent' # recent/max/average
  threshold: 0.0  # g/s
  threshold_type: 'absolute'  # absolute/relative
is_follow_up: False # True/False
reporting_delay: 2  # days
t_bw_sites:
  file: '_placeholder_str_'
  vals: [30.0]  # minutes
weather_envs:
  precip: [0.0, 0.5]
  temp: [-40.0, 40.0]
  wind: [0.0, 10.0]  
version: '2.0'
RS: 4
time: 30  # minutes