consider_daylight: False
cost:
  per_day: 0
  per_hour: 0
  per_site: 0
  upfront: 0
coverage:
  spatial: 1.0
  temporal: 1.0
deployment_type: '_placeholder_str_'
follow_up:
  preferred_method: '_placeholder_str_'
  delay: 0
  instant_threshold: '_placeholder_float_'
  instant_threshold_type: 'absolute'
  interaction_priority: 'threshold'
  min_followups: ['_placeholder_float_']
  min_followup_type: 'annual'
  min_followup_days_to_end: 0
  proportion: 1.0
  redundancy_filter: 'recent'
  threshold: 0.0
  threshold_type: 'absolute'
is_follow_up: False
label: '_placeholder_str_'
max_workday: 8
measurement_scale: '_placeholder_str_'
n_crews: '_placeholder_int_'
parameter_level: 'method'
reporting_delay: 2
scheduling:
  deployment_months: [1,2,3,4,5,6,7,8,9,10,11,12]
  deployment_years: ['_placeholder_int_']
  LDAR_crew_init_location: [-114.062, 51.044]
  home_bases_files: 'Airport_AB_Coordinates.csv'
  route_planning: False
  travel_speeds: ['_placeholder_int_']
  min_time_bt_surveys: '_placeholder_int_'
sensor:
  type: default
  QE: 0.0
  MDL: [0.01]
  mod_loc: '_placeholder_str_'
t_bw_sites:
  file: '_placeholder_str_'
  vals: [30.0]
weather_envs:
  precip: [0.0, 0.5]
  temp: [-40.0, 40.0]
  wind: [0.0, 10.0]  
version: '2.0'
RS: '_placeholder_int_'
time:  '_placeholder_int_'