parameter_level: "methods"
version: "4.0"
method_name: "_placeholder_str_"
measurement_scale: "_placeholder_str_" # site/equipment/component
deployment_type: "_placeholder_str_" # mobile/stationary/orbit
sensor:
  type: default # default/OGI_camera_zim(see User manual for MDL values)/OGI_camera_rk
  quantification_error: 0.0
  minimum_detection_limit: [0.01]
coverage:
  spatial: 1.0 # 0.0 to 1.0
  temporal: 1.0 # 0.0 to 1.0
cost:
  per_day: 0
  per_site: 0
  upfront: 0
crew_count: 0 # whole numbers
consider_daylight: False
surveys_per_year: "_placeholder_int_"
survey_time: "_placeholder_int_" # minutes
max_workday: 8 # 1 to 23
reporting_delay: 2 # days
time_between_sites:
  file: "_placeholder_str_"
  values: [30.0] # minutes
scheduling:
  deployment_months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  deployment_years: ["_placeholder_int_"]
weather_envelopes:
  precipitation: [0.0, 0.5]
  temperature: [-40.0, 40.0]
  wind: [0.0, 10.0]
is_follow_up: False # True/False
follow_up:
  preferred_method: "_placeholder_str_"
  delay: 0 # days
  instant_threshold: "_placeholder_float_" # g/s
  interaction_priority: "threshold" # threshold/proportion
  proportion: 1.0 # 0 to 1.0
  redundancy_filter: "recent" # recent/max/average
  sort_by_rate: True # True/False
  threshold: 0.0 # g/s
rolling_average:
  small_window: 7 # days
  large_window: 30 # days
  small_window_threshold: 0.0 # g/s
  large_window_threshold: 0.0 # g/s