version: "3.0"
parameter_level: "simulation_settings"
input_directory: "./inputs"
output_directory: "./outputs"
n_processes: "_placeholder_int_" # Recommend: 6
n_simulations: 2
write_data: True # True/False
make_plots: True # True/False
print_from_simulations: True # True/False
start_date: [2017, 1, 1]
end_date: [2021, 12, 31]
reference_program: P_OGI
baseline_program: P_none
pregenerate_leaks: True # True/False
preseed_random: False # True/False
