parameter_level: "simulation_settings"
version: "3.0"
input_directory: "./inputs"
output_directory: "./outputs"
baseline_program: P_none
reference_program: P_OGI
n_processes: 6 # Recommend: 6
n_simulations: 2
start_date: [2023, 1, 1]
end_date: [2027, 12, 31]
make_plots: True # True/False
print_from_simulations: True # True/False
write_data: True # True/False
pregenerate_leaks: True # True/False
preseed_random: False # True/False
outputs:
  site_visits: False
