parameter_level: "simulation_settings"
version: "4.0"
input_directory: "./inputs"
output_directory: "./outputs"
baseline_program: P_none
reference_program: P_OGI
n_processes: 6 # Recommend: 6
n_simulations: 2
print_from_simulations: True # True/False
preseed_random: False # True/False
