baseline_program: P_none
end_date:
  - 2021
  - 12
  - 31
input_directory: ./inputs
make_plots: true
n_processes: 6
n_simulations: 1
output_directory: ./outputs
parameter_level: simulation_settings
pregenerate_leaks: true
preseed_random: true
print_from_simulations: true
programs:
  P_continuous:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels:
      - Continuous
      - OGI_FU
    methods:
      Continuous:
        RS: null
        consider_daylight: false
        cost:
          per_day: 4
          per_hour: 0
          per_site: 0
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: stationary
        follow_up:
          delay: 30
          instant_threshold: 5
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: Continuous
        max_workday: 8
        measurement_scale: site
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 2
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 30.0
        time: null
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
      OGI_FU:
        RS: null
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 700
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: true
        label: OGI_FU
        max_workday: 8
        measurement_scale: component
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.5
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 45
        time: 120
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
    parameter_level: program
    program_name: P_continuous
    version: "3.0"
  P_mobile_campaigns:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels:
      - mobile_campaigns
      - OGI_FU
    methods:
      OGI_FU:
        RS: null
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 700
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: true
        label: OGI_FU
        max_workday: 8
        measurement_scale: component
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.5
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 45
        time: 120
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
      mobile_campaigns:
        RS: 4
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 100
          upfront: 0
        coverage:
          spatial: 1.0
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 45
          min_followup_type: campaign
          min_followups:
            - 1
            - 0.5
            - 0.5
            - 0.5
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: mobile_campaigns
        max_workday: 8
        measurement_scale: site
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 3
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 30.0
        time: 30
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
    parameter_level: program
    program_name: P_mobile_campaigns
    version: "3.0"
  P_mobile_proportion:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels:
      - mobile_proportion
      - OGI_FU
    methods:
      OGI_FU:
        RS: null
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 700
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: true
        label: OGI_FU
        max_workday: 8
        measurement_scale: component
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.5
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 45
        time: 120
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
      mobile_proportion:
        RS: 4
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 100
          upfront: 0
        coverage:
          spatial: 1.0
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: mobile_proportion
        max_workday: 8
        measurement_scale: site
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 3
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 30.0
        time: 30
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
    parameter_level: program
    program_name: P_mobile_proportion
    version: "3.0"
  P_mobile_threshold:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels:
      - mobile_threshold
      - OGI_FU
    methods:
      OGI_FU:
        RS: null
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 700
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: true
        label: OGI_FU
        max_workday: 8
        measurement_scale: component
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 0.5
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 45
        time: 120
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
      mobile_threshold:
        RS: 4
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 100
          upfront: 0
        coverage:
          spatial: 1.0
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 10
          threshold_type: absolute
        is_follow_up: false
        label: mobile_threshold
        max_workday: 8
        measurement_scale: site
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
            - -114.062
            - 51.044
          deployment_months:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          min_time_bt_surveys: null
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
            - 3
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
            - 30.0
        time: 30
        version: "3.0"
        weather_envs:
          precip:
            - 0.0
            - 0.5
          temp:
            - -40.0
            - 40.0
          wind:
            - 0.0
            - 10.0
    parameter_level: program
    program_name: P_mobile_threshold
    version: "3.0"
  P_none:
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
          - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    method_labels: []
    methods: {}
    parameter_level: program
    program_name: P_none
    version: "3.0"
reference_program: P_continuous
start_date:
  - 2017
  - 1
  - 1
version: "3.0"
virtual_world:
  NRd: 365
  consider_weather: false
  emissions:
    LPR: 0.0065
    consider_venting: false
    leak_dist_params:
      - -2.776
      - 1.462
    leak_dist_type: lognorm
    leak_file: test_rates.csv
    leak_file_use: sample
    max_leak_rate: 100000.0
    subtype_leak_dist_file: null
    units:
      - kilogram
      - hour
  infrastructure_file: facilities_alberta.csv
  n_init_days: null
  n_init_leaks_prob: null
  parameter_level: virtual_world
  repair_delay:
    type: default
    val:
      - 14.0
  site_samples: 50
  subtype_file: null
  version: "3.0"
  weather_file: weather_alberta.nc
  weather_is_hourly: true
write_data: true
