baseline_program: P_none
input_directory: ./inputs
n_simulations: 1
output_directory: ./outputs
parameter_level: simulation_settings
pregenerate_leaks: true
preseed_random: true
reference_program: P_OGI
version: '3.2'
