parameter_level: method
version: '2.0'
label: aircraft
module: dummy
deployment_type: mobile
measurement_scale: equipment
sensor: 
  type: default
  MDL: [0.01]
is_follow_up: False
cost:
  per_day: 10000
t_bw_sites:
  vals: [10]