parameter_level: method
version: "3.3"
label: aircraft_ex_sensor
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  mod_loc: METEC_NO_WIND
  MDL: [4, 5, 0]
cost:
  per_site: 200
coverage:
  spatial: 0.9
  temporal: 0.9
t_bw_sites:
  vals: [5]
RS: 4
time: 1
