parameter_level: method
version: "4.0"
label: OGI_FU
deployment_type: mobile
measurement_scale: component
sensor:
  # mod_loc: 'plugins.alt_sensor'
  type: default
  MDL: [1] #[0.24, 0.39] 
is_follow_up: True
cost:
  per_day: 0
  per_site: 500
t_bw_sites:
  vals: [30]
time: 120
