input_directory: ./inputs/simple_test_case_1
n_simulations: 1
output_directory: ./outputs/simple_test_case_1
parameter_level: simulation_settings
pregenerate_leaks: true
preseed_random: true
program_set_name: sample_simulations
reference_program: P_OGI
version: "4.0"
write_data: true
start_date: [2017, 1, 1]
end_date: [2021, 12, 31]
