input_directory: ./inputs
n_processes: 6
n_simulations: 1
output_directory: ./outputs
parameter_level: simulation_settings
pregenerate_leaks: true
preseed_random: true
program_set_name: sample_simulations
reference_program: P_OGI
version: "3.0"
start_date: [2017, 1, 1]
end_date: [2021, 12, 31]
